// app/(main)/landing/port-folio/page.tsx
import type { Metadata } from "next";
import PortfolioPage from "@/components/portfolio/portfolio";

export const metadata: Metadata = {
  title: "Video Token | Portfolio",
  description: "Generated by create next app",
};

export default function Portfolio() {
  return <PortfolioPage />;
}
