import type { Metadata } from "next";
import Image from "next/image";
import glow_left from "@public/images/glow_left.png"
import glow_bottom from "@public/images/glow_bottom.png"
import glow_top from "@public/images/glow_top.png"
import NavLayout from "@/layouts/trading-layout";


export const metadata: Metadata = {
    title: "Video Token",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={"w-full bg-[#161622]"}>
 
                {children}


            <div className="fixed inset-0 pointer-events-none">
                <Image
                    src={glow_left}
                    fill
                    fetchPriority="high"
                    alt="glow_right"
                    className="h-full w-full object-contain object-left-bottom"
                    priority
                />
                <Image
                    src={glow_top}
                    fill
                    fetchPriority="high"
                    alt="glow_right"
                    className="h-full w-full object-contain object-right-top"
                    priority
                />
                <Image
                    src={glow_bottom}
                    fill
                    fetchPriority="high"
                    alt="glow_right"
                    className="h-full w-full object-contain object-bottom"
                    priority
                />
            </div>
        </div>
    );
}
