import type { Metadata } from "next";
import NavLayout from "@/layouts/trading-layout";
import { Urbanist } from "next/font/google";

const urbanist = Urbanist({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-urbanist',
});

export const metadata: Metadata = {
    title: "Video Token",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${urbanist.variable} font-sans`}>
            <div className={"w-full bg-[#0A0A0A]"}>
                <NavLayout>
                    {children}
                </NavLayout>
            </div>
        </div>
    );
}
