
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Video Token | My Tokens",
    description: "Generated by create next app",
};

export default function MyTokensPage() {
  return (
    <div>
      <h1>My Tokens</h1>
    </div>
  )
}
