
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Video Token | Leaderboard",
    description: "Generated by create next app",
};


function Page() {
  return (
    <div className='text-center text-white text-3xl py-4'>LeaderBoard</div>
  )
}

export default Page
