import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import ContextProvider from '@/providers/contextProvider';
import './globals.css';

const urbanist = Urbanist({
  variable: '--font-urbanist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Video Token',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} min-w-full bg-[#161622]`}>
        <div>
          <ContextProvider>{children}</ContextProvider>
        </div>
      </body>
    </html>
  );
}
