import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Video Token | Premium",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <div className={"text-center font-medium text-3xl pt-5 text-white relative z-10"}>Premium</div>
    )
}
