import type { Metadata } from "next";
import Image from "next/image";
import glow_left from "@public/images/glow_left.png"
import glow_bottom from "@public/images/glow_bottom.png"
import glow_top from "@public/images/glow_top.png"
import DevModeNavLayout from "@/layouts/dev-mode-layout";


export const metadata: Metadata = {
    title: "Dev Mode",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={"w-full bg-[#0A0A0A]"}>
            <DevModeNavLayout>
                {children}
            </DevModeNavLayout>
        </div>
    );
}
