import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Video Token | Login",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <div className="flex flex-col items-center justify-center h-screen">
            <div className="flex flex-col items-center justify-center">
                <h1 className="text-4xl font-bold">Login</h1>
            </div>
        </div>
    )
}
