import CreateToken from '@/components/dev-mode/create-token'
import { Metadata } from 'next';
import React from 'react'


export const metadata: Metadata = {
    title: "Video Token | Create A Token",
    description: "Generated by create next app",
};

function Page() {
    return (
        <CreateToken />
    )
}

export default Page
